### ISSUE TITLE
speechkit.exceptions.RequestError: 16 Key 'xxx' was not found

### ISSUE THREAD

**Issue by patsevanton** [TikhonP/yandex-speechkit-lib-python#7]
**Describe the bug**
```
$ python long_audio_recognition.py Foundation2022.mp3 
Traceback (most recent call last):
  File "/home/user/IdeaProjects/yandex-speechkit-lib-python/examples/long_audio_recognition.py", line 20, in <module>
    session = Session.from_jwt(jwt)
  File "/home/user/IdeaProjects/yandex-speechkit-lib-python/venv/lib/python3.10/site-packages/speechkit/_auth.py", line 253, in from_jwt
    iam_token = get_iam_token(jwt_token=jwt_token)
  File "/home/user/IdeaProjects/yandex-speechkit-lib-python/venv/lib/python3.10/site-packages/speechkit/_auth.py", line 80, in get_iam_token
    raise RequestError(answer.json())
speechkit.exceptions.RequestError: 16 Key 'YANDEX_KEY_ID' was not found
```

**To Reproduce**
```
$ git clone https://github.com/TikhonP/yandex-speechkit-lib-python.git
$ cd yandex-speechkit-lib-python
$ virtualenv venv
...
$ . venv/bin/activate
$ python -m pip install -r requirements.txt
$ python -m pip install .

$ FOLDER_ID=$(yc config get folder-id)

$ yc iam service-account create --name admin
id: service-account-id
folder_id: folder_id
created_at: "2023-01-24T15:22:46.090718042Z"
name: admin

$ SA_ID=$(yc iam service-account get --name admin --format json | jq .id -r)

$  yc resource-manager folder add-access-binding --id $FOLDER_ID --role admin --subject serviceAccount:$SA_ID

$ yc iam api-key create --service-account-name admin > api-key.yaml

$ cat api-key.yaml 
api_key:
  id: api_key_id
  service_account_id: service-account-id
  created_at: "2023-01-24T15:28:05.126833595Z"
secret: YANDEX_KEY_ID

$ export YANDEX_PRIVATE_KEY=`cat ~/.ssh/id_rsa`

$ export BUCKET_NAME=yandex-speechkit-lib-python

$ export  SERVICE_ACCOUNT_ID=service-account-id

$ export  YANDEX_KEY_ID=YANDEX_KEY_ID
```

Ubuntu 22.04, Python 3.10

**Comment by tikhonp** [comment]
Hello how do you get `YANDEX_PRIVATE_KEY`? It must be key given from Yandex Cloud console, not local generated

**Comment by patsevanton** [comment]
I am sorry. I try later.
